---

## Create admin users and add their keys ##
- name: Adding new group admin
  group:
    name: admin
    state: present

- name: Adding new user ramz
  user:
    name: ramz
    comment: "ramz"
    groups: docker,admin

- name: Adding auth key
  authorized_key:
    user: ramz
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGqhoW+7ghi03JCKJ4Ny8n/8Odyg3bg9m2QACZPKzxrtpkrNWAOvEtMNMN/Z5/tY+Bnr5P6/BwLjoon8jnPdOmXXMBK8r7qK/QSI0NxS+oD1OYaGkFHe7zUDQjU9G9hZRXL3C+dRGCPaOqllsUYFDQU6QtAZZ/TunzWx+V9N0qdmEUU/Cpk5lnbAJ70YAIX/1nzSb8yzZtqE7jnsXI494MD20EvREkFAYVWZk/t0NPVrKZ5lCHLgNraYDBlri35Msy2mOvHM7duYNd6gYiiVG8plRO9zjsSCiNImJe4hY+tFaGmKjCVZA4WGhMZGL9dTMRN4k7f9CV9VZebWNN6OZv ramzthecoder@gmail.com"

- name: Add configuration block in /etc/sudoers for admin group
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '%admin        ALL=(ALL)       NOPASSWD: ALL'
